### PR TITLE
allow SDP ptime variable to accept float values

### PR DESCRIPTION
**Pull request by Mitchell-Roy**

### CODE REVIEW

**Comment by ibc** [comment]
Why did you close this PR?

**Comment by Mitchell-Roy** [comment]
I meant to open a PR on a forked version but somehow managed to open one here by accident

**Comment by ibc** [comment]
Cool. Will you contribute here later?

**Comment by Mitchell-Roy** [comment]
If I find issues or potential additions I'll be sure to bring it up here. I can reopen this PR if you'd like, not sure if you'd want this change though :)

**Comment by ibc** [comment]
Well, I don't know if I'm interested in this feature if you don't provide a PR here :)
Honestly, I expect to receive something for a project that I provide for free, specially improvements.

**Pull request closed without merging**
